---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sull'automazione ONTAP
    url: "/index.html"
  - title: Novità
    entries:
    - title: Novità dell'API REST di ONTAP
      url: "/whats-new.html"
    - title: Modifiche alle chiamate API REST ONTAP
      url: "/api-changes.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: Note legali
    url: "/legal-notices.html"
