---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: 'Ogni release di ONTAP aggiorna l"API REST ONTAP per offrirti nuove funzionalità, miglioramenti e correzioni di bug.' 
---
= Novità dell'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ogni release di ONTAP aggiorna l'API REST ONTAP per offrirti nuove funzionalità, miglioramenti e correzioni di bug.


TIP: Per ulteriori informazioni, incluse limitazioni o problemi noti, consultare la https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^] sezione. Vedere anche link:api-changes.html["Modifiche alle chiamate API REST ONTAP"] per eventuali modifiche che potrebbero influire sul software di automazione.



== ONTAP 9.18.1

La release ONTAP 9.18.1 continua ad ampliare le funzionalità dell'API REST di ONTAP con tredici nuove chiamate API. I miglioramenti si concentrano principalmente sulla sicurezza, ma includono anche un miglioramento relativo all'amministrazione dello storage.

Sicurezza:: Sono stati introdotti diversi miglioramenti alla sicurezza con l'API REST di ONTAP 9.18.1. È possibile utilizzare i nuovi endpoint di rete del cluster per visualizzare e aggiornare la configurazione della sicurezza della rete del cluster, inclusa la gestione dei certificati. Inoltre, è possibile amministrare la configurazione di sicurezza della rete HA per il traffico NVLog. La protezione autonoma contro il ransomware (ARP) è stata migliorata per consentire di visualizzare e aggiornare la funzionalità di abilitazione.
Storage:: NetApp FlexCache è una cache persistente di un volume di origine. Supporta il fan-out, in modo che sia possibile creare più di una FlexCache da un singolo volume di origine. L'API REST include il supporto per il recupero dello stato della connessione tra le istanze della cache e i volumi di origine.




== ONTAP 9.17.1

La versione ONTAP 9.17.1 continua ad ampliare le funzionalità dell'API REST ONTAP con quasi due dozzine di nuove chiamate API. Questa versione si concentra principalmente sui miglioramenti della sicurezza con aggiornamenti aggiuntivi all'elaborazione dei mediatori, ai sottosistemi NMVe e ai contenitori delle applicazioni.

Sicurezza:: Con l'API REST ONTAP 9.17.1 sono state introdotte quattro principali funzionalità di sicurezza. L'elevazione dei privilegi just-in-time (JIT) ONTAP rappresenta un miglioramento del controllo degli accessi basato sui ruoli (RBAC). Gli amministratori di cluster possono richiedere l'elevazione temporanea a un ruolo esistente, consentendo l'accesso a comandi privilegiati. La funzionalità include un solido set di opzioni di configurazione. È stato aggiunto il supporto per il gestore delle chiavi OpenStack Barbican. Questo KMS viene utilizzato per gestire le chiavi per NetApp Volume Encryption (NVE). La protezione autonoma dal ransomware (ARP) per i volumi SAN è inclusa in ONTAP 9.17.1. Statistiche dettagliate sull'entropia ARP sono disponibili tramite l'API REST. Sono state inoltre aggiunte diverse chiamate API per gestire la configurazione predefinita dei metadati SAML per un cluster.
Mediatori del cluster:: È possibile effettuare il ping del servizio cloud NetApp Console utilizzando l'API REST ONTAP . È anche possibile modificare la configurazione di un mediatore specifico utilizzando il metodo PATCH con un endpoint esistente.
NVMe:: I sottosistemi NVMe mantengono lo stato di configurazione e il controllo di accesso allo spazio dei nomi per un insieme di host connessi a NVMe. Con ONTAP 9.17.1, è possibile modificare un sottosistema NVMe utilizzando il metodo PATCH con un endpoint esistente.
Contenitori di applicazioni:: I contenitori applicativi sono una novità di ONTAP 9.17.1 e consentono il provisioning di uno o più oggetti di storage. È possibile configurare le policy e le regole necessarie per l'accesso client allo storage. È possibile effettuare il provisioning anche dei volumi FlexCache .




== ONTAP 9.16.1

ONTAP 9.16,1 include oltre due dozzine di nuove chiamate API che continuano ad espandere le funzionalità dell'API REST ONTAP. Questi miglioramenti si concentrano principalmente sulla sicurezza, ma includono anche miglioramenti relativi alle metriche e all'amministrazione dei bucket.


NOTE: L'API REST ONTAP esposta agli utenti dei sistemi NetApp ASA R2 (ASA A1K, ASA A70 e ASA A90) è diversa rispetto all'API REST fornita con tutti gli altri sistemi FAS, AFF e ASA. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/asa-r2/learn-more/rest-api-support.html["Supporto delle API REST per i sistemi ASA R2"^] .

Supporto OAuth 2,0 per Microsoft Entra ID:: Il supporto OAuth 2,0 è stato introdotto per la prima volta con ONTAP 9.14,1. Le funzionalità di OAuth 2,0 sono state migliorate con ONTAP 9.16,1 per supportare il server di autorizzazione Microsoft Entra ID (in precedenza Azure ad) con attestazioni OAuth 2,0 standard. Sono incluse due funzioni principali, come descritto di seguito.
OAuth 2,0 con gruppi come UUID:: Le attestazioni di gruppo standard Entra ID basate sui valori di stile UUID sono supportate da due nuove funzionalità con dieci nuove chiamate API:
+
--
* UUID gruppo a associazione nome gruppo (`/security/groups`)
* Associazione tra gruppo UID e ruolo (`/security/group/role-mapping`)


--
OAuth 2,0 con ruoli esterni:: Un ruolo esterno viene definito in un provider di identificazione OAUTH 2,0 definito per ONTAP. È possibile creare e amministrare relazioni di mappatura tra questi ruoli esterni e i ruoli ONTAP. Sono state aggiunte cinque nuove chiamate API.
Autenticazione Web:: L'autenticazione Web (WebAuthn) è uno standard Web per l'autenticazione sicura degli utenti basata sulla crittografia a chiave pubblica. Con ONTAP, supporta l'amministrazione di mFas resistenti al phishing tramite Gestione di sistema e l'API REST ONTAP. Sono state aggiunte sette nuove chiamate API in diversi endpoint.
Versione e aggiornamenti della protezione autonoma dal ransomware:: Sono state aggiunte due chiamate API con un nuovo endpoint per gestire il pacchetto autonomo di protezione dal ransomware utilizzato da ONTAP. Puoi visualizzare la versione e aggiornare il pacchetto di protezione autonoma dal ransomware.
Metriche dei qtree:: ONTAP 9.16,1 include una funzione opzionale di monitoraggio delle performance esteso del qtree. Con la funzione attivata, ONTAP acquisisce dati aggiuntivi, incluse le metriche di latenza e i dati storici. È stato aggiunto un nuovo endpoint per consentire il recupero dei dati sulle prestazioni.
S3 istantanee del bucket:: Sono state aggiunte quattro nuove chiamate API per creare e amministrare snapshot dei bucket S3. Ogni istantanea è un'immagine del bucket esistente al momento della creazione dell'istantanea.




== ONTAP 9.15.1

ONTAP 9.15,1 continua ad espandere le funzionalità dell'API REST ONTAP, incluso il supporto di due nuove funzionalità.

NFS su TLS:: Con questa funzione sono disponibili tre nuovi endpoint. È possibile eseguire queste chiamate API per recuperare tutte le interfacce NFS su TLS, recuperare un'interfaccia specifica tramite UUID e aggiornare le proprietà di configurazione per un'interfaccia TLS. Collettivamente, queste chiamate API forniscono un equivalente all'insieme di `vserver nfs tls interface` Comandi CLI.



CAUTION: NFS over TLS è disponibile in ONTAP 9.15.1 come anteprima pubblica. Come offerta di anteprima, questa funzionalità non è supportata per i carichi di lavoro di produzione con ONTAP 9.15.1.

Applicazioni di backup di Windows e collegamenti simbolici in stile Unix:: Quando un'applicazione di backup di Windows incontra un collegamento simbolico in stile Unix (link simbolico), il collegamento viene attraversato e i dati vengono restituiti da ONTAP e sottoposti a backup. A partire da ONTAP 9.15.1, è anche possibile eseguire il backup del collegamento simbolico anziché dei dati a cui punta. Questo può fornire diversi vantaggi, tra cui il miglioramento delle prestazioni delle applicazioni di backup. L'endpoint `/protocols/cifs/services/{svm.uuid}` è stato aggiornato per includere il nuovo parametro `backup-symlink-enabled` nell' `options` oggetto.




== ONTAP 9.14.1

La versione ONTAP 9.14.1 include oltre tre dozzine di nuove chiamate API che continuano ad espandere le funzionalità dell'API REST ONTAP. Questi endpoint supportano diverse nuove funzionalità di ONTAP e aggiornamenti alle funzionalità esistenti. Questa release si concentra principalmente sui miglioramenti alla sicurezza, ma include anche miglioramenti alle metriche NAS, QOS e delle performance.

Sicurezza:: Con ONTAP 9.14.1 sono state introdotte due funzioni di protezione principali. Open Authorization (OAuth 2,0) è un framework basato su token che può essere utilizzato per limitare l'accesso alle risorse di storage ONTAP. È possibile utilizzarlo con client che accedono a ONTAP tramite l'API REST. La configurazione può essere eseguita con qualsiasi interfaccia amministrativa di ONTAP, inclusa l'API REST. La versione ONTAP 9.14.1 include anche il supporto per Cisco Duo che fornisce l'autenticazione a due fattori per gli accessi SSH. Puoi configurare Duo per il funzionamento a livello di cluster ONTAP o SVM. Oltre a queste due nuove funzionalità, sono stati aggiunti diversi endpoint per migliorare il controllo sugli archivi chiave.
Storage persistente FPolicy:: FPolicy fornisce una piattaforma per la gestione dei criteri ONTAP. Fornisce un contenitore per i vari componenti o elementi, quali eventi e motore dei criteri. È ora possibile utilizzare l'API REST per configurare e amministrare un archivio persistente per la configurazione e gli eventi di ONTAP FPolicy. Ciascuna SVM può disporre di un unico archivio persistente condiviso per le diverse policy all'interno della SVM.
Opzioni di QOS:: Sono stati introdotti due endpoint per consentire il recupero e l'impostazione delle opzioni di QUALITÀ DEL SERVIZIO per il cluster. Ad esempio, è possibile riservare una percentuale delle risorse di elaborazione del sistema disponibili per le attività in background.
Metriche delle performance:: ONTAP conserva informazioni statistiche sulle caratteristiche operative del sistema. Queste informazioni sono presentate in un formato di database composto da tabelle e righe. Con ONTAP 9.14.1, vengono aggiunti dati di metriche aggiuntivi in diverse categorie di risorse, tra cui Fibre Channel, iSCSI, LUN e NVME. Questi dati aggiuntivi di metriche continuano a portare l'API REST ONTAP più vicina alla parità con l'API Data ONTAP (ONTAPI o ZAPI).
Miglioramenti vari:: Ci sono diversi miglioramenti aggiuntivi che possono essere utili a seconda dell'ambiente. Questi nuovi endpoint migliorano l'accesso agli iniziatori SAN e il controllo delle impostazioni della cache host, oltre a consentire l'accesso a singoli messaggi AutoSupport.




== ONTAP 9.13.1

ONTAP 9.13.1 continua ad espandere le funzionalità dell'API REST di ONTAP con oltre due dozzine di nuove chiamate API. Questi endpoint supportano le nuove funzionalità di ONTAP e i miglioramenti alle funzionalità esistenti. Questa release si concentra sui miglioramenti alla sicurezza, alla gestione delle risorse, alle opzioni di configurazione SVM avanzate e alle metriche delle performance.

Tagging delle risorse:: È possibile utilizzare i tag per raggruppare le risorse API REST. Questa operazione può essere eseguita per associare risorse correlate all'interno di un progetto o di un gruppo organizzativo specifico. L'utilizzo dei tag può aiutare a organizzare e tenere traccia delle risorse in modo più efficace.
Gruppi di coerenza:: ONTAP 9.13.1 continua ad espandere la disponibilità dei dati dei contatori delle performance. Ora puoi accedere a questo tipo di informazioni statistiche per tenere traccia delle performance storiche e della capacità dei gruppi di coerenza. Inoltre, sono stati inclusi miglioramenti che consentono di configurare e gestire le relazioni padre-figlio tra i gruppi di coerenza.
Configurazione DNS per SVM:: Gli endpoint DNS esistenti sono stati ampliati per consentire l'esecuzione della configurazione del server e del dominio DNS per le singole SVM.
Configurazione del ruolo EMS:: La funzionalità di supporto EMS esistente è stata ampliata per consentire la gestione dei ruoli e la configurazione del controllo degli accessi assegnata ai ruoli. In questo modo è possibile limitare o filtrare gli eventi e i messaggi in base alla configurazione del ruolo.
Sicurezza:: È possibile utilizzare l'API REST per configurare i profili TOTP (Time-Based One-Time Password) per gli account che accedono a ONTAP utilizzando SSH. Inoltre, gli endpoint del gestore delle chiavi sono stati ampliati per fornire un'operazione di ripristino da un server di gestione delle chiavi specificato.
Configurazione CIFS per SVM:: Gli endpoint CIFS esistenti sono stati ampliati per consentire l'aggiornamento della configurazione di una SVM specifica.
Regole del bucket S3:: Gli endpoint del bucket S3 esistenti sono stati ampliati per includere una definizione di regola. Ogni regola è un elenco di oggetti e definisce l'insieme di azioni da eseguire su un oggetto all'interno del bucket. Nel complesso, queste regole consentono di gestire meglio il ciclo di vita dei bucket S3.




== ONTAP 9.12.1

ONTAP 9.12.1 continua ad espandere le funzionalità dell'API REST di ONTAP con oltre quaranta nuove chiamate API. Questi endpoint supportano le nuove funzionalità di ONTAP e i miglioramenti alle funzionalità esistenti. Questa versione si concentra sui miglioramenti alla sicurezza e alle funzionalità NAS.

Miglioramenti della sicurezza:: Amazon Web Services include un servizio di gestione delle chiavi che fornisce storage sicuro per chiavi e altri segreti. È possibile accedere a questo servizio tramite l'API REST per consentire a ONTAP di memorizzare in modo sicuro le proprie chiavi di crittografia nel cloud. Inoltre, è possibile creare ed elencare le chiavi di autenticazione utilizzate con NetApp Storage Encryption.
Active Directory:: È possibile gestire gli account Active Directory definiti per un cluster ONTAP. Ciò include la creazione di nuovi account, nonché la visualizzazione, l'aggiornamento e l'eliminazione degli account.
Criteri di gruppo CIFS:: L'API REST è stata migliorata per supportare la creazione e la gestione delle policy di gruppo CIFS. Le informazioni di configurazione sono disponibili e amministrate tramite oggetti di policy di gruppo che vengono applicati a tutte le SVM o a specifiche SVM.




== ONTAP 9.11.1

ONTAP 9.11.1 continua ad espandere le funzionalità dell'API REST di ONTAP con quasi un centinaio di nuove chiamate API. Questi endpoint supportano le nuove funzionalità di ONTAP e i miglioramenti alle funzionalità esistenti.

RBAC granulare:: La funzionalità RBAC (Role-Based Access Control) di ONTAP è stata migliorata per fornire una granularità aggiuntiva. È possibile utilizzare i ruoli tradizionali o creare nuovi ruoli personalizzati in base alle esigenze tramite l'API REST. Ogni ruolo è associato a uno o più privilegi, ciascuno dei quali identifica una chiamata API REST o un comando CLI insieme al livello di accesso. Sono disponibili nuovi livelli di accesso per i ruoli REST, ad esempio `read_create` e. `read_modify`. Questo miglioramento fornisce la parità con l'API Data ONTAP (ONTAPI o ZAPI) e supporta la migrazione dei clienti all'API REST. Vedere link:rest/rbac_overview.html["Sicurezza RBAC"] per ulteriori informazioni.
Contatori delle performance:: Le precedenti release di ONTAP hanno mantenuto informazioni statistiche sulle caratteristiche operative del sistema. Con la versione 9.11.1, queste informazioni sono state migliorate e sono ora disponibili tramite l'API REST. Un amministratore o un processo automatizzato può accedere ai dati per determinare le performance del sistema. Le informazioni statistiche, gestite dal sottosistema di gestione dei contatori, vengono presentate in un formato di database utilizzando tabelle e righe. Questo miglioramento avvicina l'API REST ONTAP alla parità con l'API Data ONTAP (ONTAPI o ZAPI).
Gestione degli aggregati:: La gestione degli aggregati di storage ONTAP è stata migliorata. È possibile utilizzare gli endpoint REST aggiornati per spostare gli aggregati online e offline e gestire le parti di ricambio.
Funzionalità della subnet IP:: La funzionalità di rete ONTAP è stata ampliata per includere il supporto per le subnet IP. L'API REST consente di accedere alla configurazione e alla gestione delle subnet IP all'interno di un cluster ONTAP.
Verifica di più amministratori:: La funzione di verifica di più amministratori fornisce un framework di autorizzazione flessibile per proteggere l'accesso ai comandi o alle operazioni ONTAP. È possibile definire regole che identificano i comandi con restrizioni. Quando un utente richiede l'accesso a un comando specifico, l'approvazione può essere concessa da più amministratori di ONTAP, a seconda dei casi.
Miglioramenti di SnapMirror:: La funzionalità di SnapMirror è stata migliorata in diverse aree, tra cui la pianificazione. La parità di relazione SnapVault è stata aggiunta in una relazione DP con ONTAP 9.11.1. Inoltre, la funzione di accelerazione disponibile con L'API REST ha raggiunto la parità con l'API Data ONTAP (ONTAPI o ZAPI). A questo scopo, è disponibile il supporto per la creazione e la gestione di copie snapshot in blocco.
Pool di storage:: Sono stati aggiunti diversi endpoint per fornire l'accesso ai pool di storage ONTAP. È incluso il supporto per la creazione e l'elenco dei pool di storage in un cluster, nonché per l'aggiornamento e l'eliminazione di pool specifici in base all'ID.
Supporto della cache dei name Services:: I name service ONTAP sono stati migliorati per supportare il caching, migliorando le performance e la resilienza. È ora possibile accedere alla configurazione della cache dei name service tramite l'API REST. Le impostazioni possono essere applicate a più livelli, inclusi host, utenti unix, gruppi unix e netgroup.
Tool di reporting ONTAPI:: Il tool di reporting ONTAPI aiuta clienti e partner a identificare l'utilizzo di ONTAPI nel proprio ambiente. Questo tool fornisce preziose informazioni per i clienti che pianificano la migrazione da ONTAPI all'API REST ONTAP.




== ONTAP 9.10.1

ONTAP 9.10.1 continua ad espandere le funzionalità dell'API REST di ONTAP. Sono stati aggiunti oltre cento nuovi endpoint per supportare le nuove funzionalità di ONTAP e i miglioramenti alle funzionalità esistenti. Di seguito viene presentato un riepilogo dei miglioramenti apportati all'API REST.

Gruppo di coerenza dell'applicazione:: Un gruppo di coerenza è un insieme di volumi raggruppati quando si eseguono determinate operazioni, ad esempio uno snapshot. Questa funzionalità estende la stessa coerenza del crash e l'integrità dei dati implicita con operazioni a volume singolo in un insieme di volumi. È utile per applicazioni di workload multi-volume di grandi dimensioni.
Migrazione SVM:: È possibile migrare una SVM da un cluster di origine a un cluster di destinazione. I nuovi endpoint offrono un controllo completo, inclusa la possibilità di sospendere, riprendere, recuperare lo stato e interrompere un'operazione di migrazione.
Cloning e gestione dei file:: La clonazione e la gestione dei file a livello di volume sono state migliorate. I nuovi endpoint REST supportano le operazioni di spostamento, copia e divisione dei file.
Controllo S3 migliorato:: Il controllo degli eventi S3 è un miglioramento della sicurezza che consente di tenere traccia e registrare determinati eventi S3. È possibile impostare un selettore di eventi di audit S3 per SVM per bucket.
Difesa ransomware:: ONTAP rileva i file potenzialmente contenenti una minaccia ransomware. È possibile recuperare un elenco di questi file sospetti e rimuoverli da un volume.
Miglioramenti di sicurezza vari:: Esistono diversi miglioramenti generali alla sicurezza che espandono i protocolli esistenti e introducono nuove funzionalità. Sono stati apportati miglioramenti a IPSEC, gestione delle chiavi, configurazione SSH e permessi dei file.
Domini CIFS e gruppi locali:: È stato aggiunto il supporto per i domini CIFS a livello di cluster e SVM. È possibile recuperare la configurazione del dominio, nonché creare e rimuovere i domain controller preferiti.
Analisi dei volumi estesa:: Le metriche e le analisi dei volumi sono state ampliate attraverso endpoint aggiuntivi per supportare file, directory e utenti top.
Miglioramenti del supporto:: Il supporto è stato migliorato grazie a diverse nuove funzionalità. Gli aggiornamenti automatici consentono di mantenere aggiornati i sistemi ONTAP scaricando e applicando gli ultimi aggiornamenti software. È inoltre possibile recuperare e gestire i core dump di memoria generati da un nodo.




== ONTAP 9.9.1

ONTAP 9.9.1 continua ad espandere le funzionalità dell'API REST di ONTAP. Esistono nuovi endpoint API per le funzionalità ONTAP esistenti, tra cui set di porte SAN e sicurezza delle directory dei file VServer. Inoltre, gli endpoint sono stati aggiunti per supportare le nuove funzionalità e i miglioramenti di ONTAP 9.9.1. E la relativa documentazione è stata migliorata. Di seguito viene presentato un riepilogo dei miglioramenti.

Mappatura di ONTAPI all'API REST di ONTAP 9:: Per facilitare la transizione del codice di automazione ONTAP all'API REST, NetApp fornisce la documentazione di mappatura API. Questo riferimento include un elenco di chiamate ONTAPI e l'equivalente API REST per ciascuna. Il documento di mappatura è stato aggiornato per includere i nuovi endpoint API di ONTAP 9.9.1. Vedere link:migrate/mapping.html["ONTAPI per il mapping API REST"] per ulteriori informazioni.
Endpoint API per le nuove funzionalità principali di ONTAP 9.9.1:: AlL'API REST è stato aggiunto il supporto per le nuove funzionalità di ONTAP 9.9.1 non disponibili tramite l'API ONTAPI. Include il supporto per igroups nidificati e Google Cloud Key Management Services.
Supporto migliorato per la transizione A REST da ONTAPI:: Un numero maggiore di chiamate ONTAPI legacy ora dispone di equivalenti API REST corrispondenti. Ciò include utenti e gruppi Unix locali, gestione della sicurezza dei file NTFS senza la necessità di un client, set di porte SAN e attributi di spazio dei volumi. Queste modifiche sono incluse anche nella documentazione aggiornata di ONTAPI to REST mapping.
Documentazione online migliorata:: La pagina di riferimento della documentazione online di ONTAP ora include etichette che indicano la release di ONTAP al momento dell'introduzione di ciascun endpoint O parametro REST, incluse le nuove versioni di ONTAP 9.9.1.




== ONTAP 9.8

ONTAP 9.8 include diverse nuove funzioni che consentono di automatizzare la distribuzione e la gestione dei sistemi di storage ONTAP. Inoltre, è stato migliorato il supporto per la transizione A REST dall'API ONTAPI legacy.

Mappatura di ONTAPI all'API REST di ONTAP 9:: Per aggiornare l'automazione ONTAPI, NetApp fornisce un elenco di chiamate ONTAPI che richiedono uno o più parametri di input, oltre a una mappatura di tali chiamate alla chiamata API REST ONTAP 9 equivalente. Vedere link:migrate/mapping.html["ONTAPI per il mapping API REST"] per ulteriori informazioni.
Endpoint API per le nuove funzioni ONTAP 9.8:: Il supporto per le nuove funzioni di ONTAP 9.8 non disponibili tramite ONTAPI è stato aggiunto all'API REST. Ciò include il supporto delle API REST per bucket e servizi ONTAP S3, SnapMirror Active Sync (in precedenza SnapMirror Business Continuity) e file system analytics.
Supporto esteso per una maggiore sicurezza:: La sicurezza è stata migliorata grazie al supporto di diversi servizi e protocolli, tra cui Azure Key Vault, Google Cloud Key Management Services, IPSec e richieste di firma del certificato.
Miglioramenti per migliorare la semplicità:: ONTAP 9.8 offre flussi di lavoro più efficienti e moderni utilizzando l'API REST. Ad esempio, gli aggiornamenti del firmware con un clic sono ora disponibili per diversi tipi di firmware.
Documentazione online migliorata:: La pagina della documentazione online di ONTAP include etichette che indicano la release di ONTAP in cui sono stati introdotti ogni endpoint o parametro REST, incluse quelle nuove nel 9,8.
Supporto migliorato per la transizione A REST da ONTAPI:: Più chiamate ONTAPI legacy ora hanno equivalenti API REST corrispondenti. È inoltre disponibile una documentazione che consente di identificare l'endpoint REST da utilizzare al posto di una chiamata ONTAPI esistente.
Metriche delle performance estese:: Le metriche delle performance per L'API REST sono state ampliate per includere diversi nuovi oggetti di storage e di rete.




== ONTAP 9.7

ONTAP 9.7 estende l'ambito funzionale dell'API REST di ONTAP introducendo tre nuove categorie di risorse, ciascuna con diversi endpoint REST:

* NDMP
* Archivio di oggetti
* SnapLock


ONTAP 9.7 introduce inoltre uno o più nuovi endpoint REST in diverse categorie di risorse esistenti:

* Cluster
* NAS
* Networking
* NVMe
* SAN
* Sicurezza
* Storage
* Supporto




== ONTAP 9.6

ONTAP 9.6 estende notevolmente il supporto delle API REST introdotto originariamente in ONTAP 9.4. L'API REST di ONTAP 9.6 supporta la maggior parte delle attività di configurazione e amministrazione di ONTAP.

Le API REST in ONTAP 9.6 includono le seguenti aree chiave e molte altre:

* Configurazione del cluster
* Configurazione del protocollo
* Provisioning
* Monitoraggio delle performance
* Protezione dei dati
* Gestione dei dati consapevole dell'applicazione

