---
sidebar: sidebar 
permalink: resources/overview_categories.html 
keywords: resources, resource categories 
summary:  
---
= Panoramica delle categorie di risorse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le risorse disponibili tramite le API REST ONTAP sono organizzate per categorie. Ciascuna delle categorie di risorse include una breve descrizione insieme a considerazioni di utilizzo aggiuntive, ove appropriato.

Le risorse RIMANENTI descritte nel riepilogo si basano sull'ultima versione del prodotto. Per informazioni più dettagliate sulle modifiche apportate nelle versioni precedenti, vedere link:../whats-new.html["Novità dell'API REST di ONTAP"] così come il https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^].


TIP: Per molti degli endpoint REST, è possibile includere una chiave UUID come parte della stringa di percorso per accedere a una specifica istanza dell'oggetto. Tuttavia, in molti casi è anche possibile accedere agli oggetti utilizzando un valore di proprietà su un parametro di query.

.Informazioni correlate
* link:../reference/api_reference.html["Riferimento API"]

