---
sidebar: sidebar 
permalink: resources/overview_categories.html 
keywords: resources, resource categories 
summary: 'Le risorse disponibili tramite l"API REST di ONTAP sono organizzate in categorie, come mostrato nella pagina di documentazione dell"API di ONTAP.' 
---
= Panoramica delle categorie di risorse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le risorse disponibili tramite l'API REST ONTAP sono organizzate in categorie, come mostrato nella documentazione online dell'API ONTAP. Di seguito viene presentata una breve descrizione di ciascuna delle risorse e, se necessario, ulteriori considerazioni sull'utilizzo.

Le risorse RIMANENTI descritte in questo riepilogo si basano sull'ultima versione del prodotto. Per informazioni sulle modifiche apportate dalle release precedenti, vedere link:../whats_new.html["Novità dell'API REST di ONTAP"] così come il https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^].


TIP: Per molti degli endpoint REST, è possibile includere una chiave UUID come parte della stringa di percorso per accedere a una specifica istanza dell'oggetto. Tuttavia, è anche possibile accedere agli oggetti utilizzando un valore di proprietà su un parametro di query.

.Informazioni correlate
* link:../rest/object_references_and_access.html["Ulteriori considerazioni DI RIPOSO"]
* link:../reference/api_reference.html["Riferimento API"]

