---
sidebar: sidebar 
permalink: migrate/blogs_migrate.html 
keywords: blogs, blog articles 
summary: 'Sono disponibili diversi articoli del blog per aiutarti a comprendere meglio come migrare da ONTAPI all"API REST di ONTAP.' 
---
= Articoli del blog
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sono disponibili diversi articoli del blog per aiutarti a comprendere meglio come migrare da ONTAPI all'API REST di ONTAP.

.ONTAPI to REST Mapping
NetApp fornisce il supporto per il passaggio dall'API ONTAPI proprietaria all'API REST ONTAP attraverso la documentazione di mappatura.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["netapp.io/2020/12/17/ontapi-to-rest-mapping"^]

.Trasforma la tua automazione in API REST ONTAP di ONTAPI
Sono disponibili diverse tecnologie che consentono di trasformare l'ambiente di automazione ONTAP in base all'API REST.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/["www.netapp.com/blog/transform-automation-ontap-rest-api"^]

.Utilizzo del pass-through CLI privato con l'API REST di ONTAP
Per consentire agli utenti di CLI e ONTAP di passare all'API REST di ONTAP, ONTAP fornisce un endpoint REST API privato che può essere utilizzato per accedere a qualsiasi comando CLI.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api"^]

.Transizione da ONTAPI utilizzando ONTAPI Usage Reporting Tool
NetApp offre uno strumento per aiutare clienti e partner a passare all'API REST di ONTAP.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool"^]
