---
sidebar: sidebar 
permalink: migrate/migration-considerations.html 
keywords: migrate, mirgate to rest api, snapdiff 
summary: 'Prima di eseguire la migrazione all"API REST di ONTAP dall"API ONTAPI (ZAPI) o dalla CLI di ONTAP, è necessario prendere in considerazione diversi aspetti.' 
---
= Scopri come migrare all'API REST di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'API ONTAPI (ZAPI) è il set originale di chiamate proprietarie incluse nel software NetApp ONTAP .  L'API è fornita tramite Network Manageability SDK e supporta l'automazione delle attività di amministrazione e gestione dell'archiviazione dei dati.  Se si utilizza ONTAPI, è opportuno pianificare la migrazione all'API REST ONTAP per sfruttare il set di funzionalità ONTAP ampliato disponibile con l'API REST.



[[general-design-differences]]
== Differenze di progettazione generali

L'API REST di ONTAP e l'interfaccia della riga di comando hanno un design fondamentalmente diverso. I comandi e i parametri CLI non vengono mappati direttamente alle chiamate API REST. E anche laddove vi sia una somiglianza, i dettagli dei parametri di input possono essere diversi. Ad esempio, le unità numeriche possono essere specificate in byte o utilizzando un suffisso (ad esempio KB). Vedere link:../rest/input_variables.html["Variabili di input che controllano una richiesta API"] e. link:../reference/api_reference.html["Riferimento API"] per ulteriori informazioni.



[[data-svms-exposed-through-the-rest-api]]
== SVM di dati esposti attraverso l'API REST

ONTAP supporta diversi tipi di macchine virtuali per lo storage (SVM). Tuttavia, solo le SVM dei dati vengono esposte direttamente attraverso l'API REST di ONTAP. Le informazioni di configurazione che descrivono il cluster e i nodi sono disponibili attraverso l'API REST, tuttavia il cluster e i nodi non vengono trattati come SVM separate.



[[access-the-ontap-cli-through-the-rest-api]]
== Accedere all'interfaccia utente di ONTAP tramite l'API REST

Per assistere gli utenti delle API ONTAPI e della CLI nella transizione all'API REST di ONTAP, ONTAP mette a disposizione un endpoint REST per l'accesso all'interfaccia CLI di ONTAP. È possibile utilizzare questa funzionalità pass-through per eseguire qualsiasi comando CLI.  L'utilizzo dell'endpoint REST viene restituito nei dati AutoSupport in modo che NetApp possa identificare le lacune nell'API REST e apportare miglioramenti nelle future release di ONTAP.

Per eseguire un comando CLI, è necessario effettuare una chiamata API REST formata correttamente in base alle regole relative a quanto segue:

* Percorsi di risorse
* Nomi dei campi
* Metodi HTTP


Il percorso delle risorse di base per l'accesso alla CLI è `/private/cli`. Fare riferimento alla pagina della documentazione online dell'API ONTAP per informazioni dettagliate sull'accesso all'interfaccia utente attraverso l'API REST. NetApp gestisce anche un repository GitHub contenente esempi di codice e altre informazioni utili. Vedere https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["Repository GitHub di ONTAP REST Python - esempi di pass-through CLI"^] per ulteriori informazioni.



[[changes-to-snapdiff-availability-in-ontapi]]
== Modifiche alla disponibilità di SnapDiff in ONTAPI

SnapDiff v1 e v2 si basano sul framework di gestione ONTAPI (ZAPI) e presentano alcune limitazioni di usabilità con determinate versioni di ONTAP. L'API SnapDiff v3 non utilizza ONTAPI ed è supportata con ONTAP 9.8 e versioni successive. La disponibilità dell'API SnapDiff tra le versioni di ONTAP è definita come segue:

* ONTAP 9.7 e versioni precedenti: v1 e v2 (solo ONTAPI)
* ONTAP 9.8 e versioni successive: v1, v2 e v3. Si applicano alcune limitazioni; consulta la  https://kb.netapp.com/on-prem/ontap/DP/SnapDiff/SnapDiff-KBs/FAQ_SnapDiff_Support_in_ONTAP["FAQ: SnapDiff Supporto in ONTAP"^] per maggiori dettagli sul supporto SnapDiff in base alla versione di ONTAP.


Dovresti verificare che le tue applicazioni di backup supportino SnapDiff e conoscere eventuali limitazioni di interoperabilità in base alla versione di ONTAP che stai usando. Vedi anche il  https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^] per ulteriori informazioni.



[[related-information]]
== Informazioni correlate

* link:../get-started/ontap_automation_options.html["Comprendere le opzioni di automazione di ONTAP"]
* https://mysupport.netapp.com/info/communications/ECMLP2880232.html["CPC-00410 rinvio dell'annuncio di fine disponibilità di ONTAPI (ZAPI)"^]
* https://kb.netapp.com/onprem/ontap/dm/REST_API/FAQs_on_ZAPI_to_ONTAP_REST_API_transformation_for_CPC_(Customer_Product_Communiques)_notification["Domande frequenti sulla trasformazione delle API REST da ZAPI a ONTAP per CPC"^]
* https://kb.netapp.com/on-prem/ontap/DP/SnapDiff/SnapDiff-KBs/FAQ_SnapDiff_Support_in_ONTAP["FAQ: SnapDiff Supporto in ONTAP"^]

