---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: 'Sono disponibili diverse risorse aggiuntive a cui è possibile accedere per ottenere assistenza e ottenere ulteriori informazioni su come automatizzare l"implementazione e l"amministrazione dei sistemi storage ONTAP.' 
---
= Risorse aggiuntive
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sono disponibili diverse risorse aggiuntive per aiutarti ad automatizzare la distribuzione e l'amministrazione dei tuoi sistemi storage ONTAP.



== Risorse di ONTAP 9

* Fornisce la documentazione per la famiglia di prodotti ONTAP 9.
+
https://docs.netapp.com/us-en/ontap-family/["Documentazione del prodotto ONTAP 9"^]

* Note sulla versione di ONTAP 9 con informazioni sulla versione corrente.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^]

* Include documentazione e altri link utili per pianificare, amministrare e supportare ONTAP 9.
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["Risorse per manager di sistema ONTAP e ONTAP"^]

* Accedi alle note di rilascio e ad altra documentazione per le release precedenti di ONTAP.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Libreria di prodotti ONTAP 9"^]





== Risorse per sviluppatori di ONTAP 9

* Aiuta a iniziare con Ansible in un ambiente DevOps.
+
https://www.netapp.com/devops-solutions/ansible/["Soluzioni NetApp Ansible DevOps"^]

* Fornisce le chiamate ONTAPI principali e un mapping alle chiamate API REST equivalenti. Selezionare la release ONTAP appropriata.
+
link:../migrate/mapping.html["ONTAPI per il mapping API REST"]

* Il pacchetto NetApp Python Client Library di PyPI.
+
https://pypi.org/project/netapp-ontap["PyPI: NetApp ONTAP"^]

* Documentazione per NetApp Python Client Library.
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html["Documentazione PCL NetApp per 9.14.1"^]

* Fornisce le risorse e la documentazione necessarie per utilizzare l'API REST di ONTAP.
+
https://devnet.netapp.com/restapi.php["Rete di sviluppatori NetApp: API RESTful di ONTAP"^]





== Articoli del blog

* Il pass-through CLI fornisce una tecnica per l'esecuzione dei comandi CLI ONTAP utilizzando l'API REST.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["Utilizzo del pass-through CLI privato con l'API REST di ONTAP"^]

* Se non hai ancora utilizzato Ansible per l'automazione ONTAP, questo è un buon punto di partenza.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["Introduzione a NetApp e Ansible: Installare Ansible"^]





== Video

* Una buona introduzione alla libreria client Python di NetApp e come iniziare a scrivere codice utilizzando la libreria.
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss["Guida introduttiva alla libreria client di NetApp ONTAP Python"^]

* Questo video è disponibile anche tramite NetApp TV all'indirizzo link:https://tv.netapp.com/detail/video/6217195551001["Moduli certificati Ansible"^].
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Panoramica sui moduli certificati Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]




== Risorse NetApp

* Accesso a strumenti per la risoluzione dei problemi, documentazione e assistenza tecnica.
+
https://mysupport.netapp.com/["Supporto NetApp"^]

* Requisiti di accesso e informazioni sulla compatibilità relativi all'utilizzo di ONTAP 9 e dell'API REST di ONTAP.
+
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]

* Accedi a report tecnici, white paper e altri documenti.
+
http://www.netapp.com/us/library/index.aspx["Libreria NetApp di report tecnici e white paper"^]


