---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: 'Sono disponibili diverse risorse aggiuntive a cui è possibile accedere per ottenere assistenza e ottenere ulteriori informazioni su come automatizzare l"implementazione e l"amministrazione dei sistemi storage ONTAP.' 
---
= Risorse aggiuntive
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sono disponibili diverse risorse aggiuntive a cui è possibile accedere per ottenere assistenza e ottenere ulteriori informazioni su come automatizzare l'implementazione e l'amministrazione dei sistemi storage ONTAP.



== Risorse di ONTAP 9

* https://docs.netapp.com/us-en/ontap-family/["Documentazione del prodotto ONTAP 9"^]
+
Fornisce la documentazione per la famiglia di prodotti ONTAP 9.

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^]
+
Note sulla versione di ONTAP 9 con informazioni sulla versione corrente.

* https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["Risorse per manager di sistema ONTAP e ONTAP"^]
+
Include documentazione e altri link utili per pianificare, amministrare e supportare ONTAP 9.

* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Libreria di prodotti ONTAP 9"^]
+
Accedi alle note di rilascio e ad altra documentazione per le release precedenti di ONTAP.





== Risorse per sviluppatori di ONTAP 9

* link:../migrate/mapping.html["ONTAPI per il mapping API REST"]
+
Fornisce le chiamate ONTAPI principali e un mapping alle chiamate API REST equivalenti. Selezionare la release ONTAP appropriata.

* https://pypi.org/project/netapp-ontap["PyPI: NetApp ONTAP"^]
+
Il pacchetto NetApp Python Client Library di PyPI.

* https://library.netapp.com/ecmdocs/ECMLP2885777/html/index.html["Documentazione NetApp PCL per 9.13.1"^]
+
Documentazione per NetApp Python Client Library.

* https://devnet.netapp.com/restapi.php["Rete di sviluppatori NetApp: API RESTful di ONTAP"^]
+
Fornisce le risorse e la documentazione necessarie per utilizzare l'API REST di ONTAP, inclusa la libreria client Python di ONTAP.





== Video

* https://www.youtube.com/watch?v=Wws3SB5d9Ss["Guida introduttiva alla libreria client di NetApp ONTAP Python"^]
+
Buona introduzione alla libreria client NetApp Python e come iniziare a scrivere codice utilizzando la libreria.





== Risorse NetApp

* https://mysupport.netapp.com/["Supporto NetApp"^]
+
Accesso a strumenti per la risoluzione dei problemi, documentazione e assistenza tecnica.

* https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
+
Requisiti di accesso e informazioni sulla compatibilità relativi all'utilizzo di ONTAP 9 e dell'API REST di ONTAP.

* http://www.netapp.com/us/library/index.aspx["Libreria NetApp di report tecnici e white paper"^]
+
Accedi a report tecnici, white paper e altri documenti.


