---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation, online reference, swagger 
summary: 'Il riferimento API contiene dettagli sulle chiamate API REST ONTAP, inclusi i metodi HTTP, i parametri di input e le risposte. Questo riferimento completo è utile quando si sviluppano applicazioni di automazione utilizzando l"API REST.' 
---
= Riferimento API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il riferimento API contiene dettagli sulle chiamate API REST ONTAP, inclusi i metodi HTTP, i parametri di input e le risposte. Questo riferimento completo è utile quando si sviluppano applicazioni di automazione utilizzando l'API REST.


NOTE: È possibile accedere alla documentazione di riferimento dell'API REST da uno dei vari siti basati sulla release ONTAP. Una copia della documentazione equivalente è disponibile anche tramite l'interfaccia utente Swagger nel sistema ONTAP locale.



== Accedi alla documentazione di riferimento dell'API ONTAP online

È possibile accedere alla documentazione corrente https://docs.netapp.com/us-en/ontap-restapi/ontap/getting_started_with_the_ontap_rest_api.html["Riferimento all'API REST ONTAP"^] online. È inoltre disponibile un selettore di versione per accedere alle versioni precedenti della documentazione basata sulla versione ONTAP.



== Accedere alla documentazione di riferimento dell'API ONTAP tramite l'interfaccia utente Swagger

È possibile accedere alla documentazione dell'API REST ONTAP tramite l'interfaccia utente Swagger nel sistema ONTAP locale.

.Prima di iniziare
È necessario disporre di quanto segue:

* Indirizzo IP o nome host della LIF di gestione del cluster ONTAP
* Nome utente e password di un account autorizzato ad accedere all'API REST di ONTAP


.Fasi
. Digitare l'URL nel browser e premere *Invio*:
+
`https://<ip_address>/docs/api`

. Accedi utilizzando l'account ONTAP.
+
Viene visualizzata la pagina della documentazione API ONTAP con le chiamate API organizzate in base alle principali categorie di risorse.

. Come esempio di una singola chiamata API, scorrere verso il basso fino alla categoria *cluster* e fare clic su *GET /cluster*.

