---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation 
summary: 'Il riferimento API contiene i dettagli relativi a tutte le chiamate API REST ONTAP, inclusi i metodi HTTP, i parametri di input e le risposte. Questo riferimento completo è utile quando si sviluppano applicazioni di automazione utilizzando l"API REST.' 
---
= Riferimento API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il riferimento API contiene i dettagli relativi a tutte le chiamate API REST ONTAP, inclusi i metodi HTTP, i parametri di input e le risposte. Questo riferimento completo è utile quando si sviluppano applicazioni di automazione utilizzando l'API REST.


NOTE: È possibile accedere al contenuto di riferimento API online nel sistema ONTAP locale o a una copia statica della documentazione gestita da NetApp.



== Accedere alla pagina di documentazione dell'API ONTAP

[role="lead"]
È possibile accedere alla pagina della documentazione online dell'API ONTAP nel sistema ONTAP locale.

.Prima di iniziare
È necessario disporre di quanto segue:

* Indirizzo IP o nome host della LIF di gestione del cluster ONTAP
* Nome utente e password di un account autorizzato ad accedere all'API REST di ONTAP


.Fasi
. Digitare l'URL nel browser e premere *Invio*:
+
`https://<ip_address>/docs/api`

. Accedi utilizzando l'account ONTAP.
+
Viene visualizzata la pagina della documentazione API ONTAP con le chiamate API organizzate in base alle principali categorie di risorse.

. Come esempio di una singola chiamata API, scorrere verso il basso fino alla categoria *cluster* e fare clic su *GET /cluster*.




== Accedere a una copia della documentazione di riferimento dell'API REST di ONTAP

[role="lead"]
È possibile accedere a una copia della documentazione di riferimento dell'API REST di ONTAP attraverso i collegamenti riportati di seguito. La documentazione di riferimento API è gestita dalla release di ONTAP.

* https://library.netapp.com/ecmdocs/ECMLP2885799/html/["ONTAP 9.13.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2884821/html/["ONTAP 9.12.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2882307/html/["ONTAP 9.11.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2879871/html/["ONTAP 9.10.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2876964/html/["ONTAP 9.9.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2874708/html/["ONTAP 9.8"^]
* https://library.netapp.com/ecmdocs/ECMLP2862544/html/["ONTAP 9.7"^]
* https://library.netapp.com/ecmdocs/ECMLP2856304/html/["ONTAP 9.6"^]


.Informazioni correlate
https://devnet.netapp.com/restapi.php["DevNet di NetApp: API REST di ONTAP"^]
