---
sidebar: sidebar 
permalink: sw-tools/learn-about-nmsdk.html 
keywords: netapp manageability sdk, oncommand workflow automation, oncommand wfa, ontapi, zapi 
summary: 'L"SDK per la gestione NetApp fornisce un set di chiamate API ONTAPI per lo sviluppo di applicazioni per monitorare e gestire lo storage ONTAP. Insieme al pacchetto OnCommand Workflow Automation, l"SDK supporta i tuoi sforzi per automatizzare la gestione dei tuoi sistemi ONTAP.' 
---
= Ulteriori informazioni sull'SDK per la gestione NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'SDK per la gestione NetApp fornisce un set di chiamate API ONTAPI per lo sviluppo di applicazioni per monitorare e gestire lo storage ONTAP. Insieme al pacchetto OnCommand Workflow Automation, l'SDK supporta i tuoi sforzi per automatizzare la gestione dei tuoi sistemi ONTAP.


NOTE: Sebbene NetApp Manageability SDK e OnCommand Workflow Automation continuino a essere supportati, l'API REST ONTAP è la tecnologia preferita e strategica da utilizzare per automatizzare i sistemi ONTAP . Vedere link:../migrate/migration-considerations.html["Migrare da ONTAPI all'API REST"] per maggiori informazioni.

.Scaricare l'SDK
È possibile scaricare l'SDK per la gestione NetApp dal sito di supporto NetApp. L'SDK supporta diversi linguaggi sul lato client, tra cui: Python, PowerShell, C, C++, Java, C#, VB. NET e Ruby. Assicurati di esaminare lo strumento della matrice di interoperabilità per informazioni sull'SDK per la gestione NetApp e sul modo in cui è supportato con la tua versione di ONTAP.

.USA OnCommand Workflow Automation
Puoi anche utilizzare l'API fornita con SDK per automatizzare le attività di gestione senza scrivere script. OnCommand Workflow Automation (OnCommand Wfa) fornisce diversi workflow preconfezionati per implementare ed eseguire le attività di gestione.

.Informazioni correlate
* https://mysupport.netapp.com/site/["Sito di supporto NetApp"^]
* https://www.netapp.com/company/interoperability/["Tool di matrice di interoperabilità NetApp"^]
* https://mysupport.netapp.com/documentation/docweb/index.html?productID=63638&language=en-US["Documentazione SDK per la gestione NetApp"^]
* https://docs.netapp.com/us-en/workflow-automation/["Documentazione OnCommand Workflow Automation"^]

