---
sidebar: sidebar 
permalink: workflows/prepare_workflows.html 
keywords: workflows, preparation, prepare to use workflows 
summary: Prima di utilizzare i flussi di lavoro ONTAP con una distribuzione live, è necessario acquisire familiarità con la struttura e il formato dei flussi di lavoro. 
---
= Preparati a utilizzare i flussi di lavoro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario conoscere la struttura e il formato dei flussi di lavoro prima di utilizzarli con una distribuzione ONTAP in tempo reale.



== Introduzione

Un _workflow_ è una sequenza di uno o più passaggi necessari per eseguire un'attività o un obiettivo amministrativo specifico. I flussi di lavoro di ONTAP includono i passaggi fondamentali e i parametri necessari per eseguire ciascuna attività. Forniscono un punto di partenza per personalizzare il vostro ambiente di automazione ONTAP.

.Tipi di passo
Ciascuna fase di un flusso di lavoro ONTAP è di uno dei seguenti tipi:

* REST API Call (con dettagli come ad esempio CURL e JSON)
* Eseguire o richiamare un altro flusso di lavoro ONTAP
* Attività correlate a varie (ad esempio, prendere una decisione di configurazione)


.Chiamate API REST
La maggior parte dei passaggi del flusso di lavoro sono chiamate API REST. Questi passaggi utilizzano un formato comune che include un esempio di arricciatura e altre informazioni. Vedere link:../reference/api_reference.html["Riferimento API"] Per ulteriori informazioni sulle chiamate API REST.

.Flussi di lavoro a fase singola
Un flusso di lavoro può contenere un solo passaggio. Questi _flussi di lavoro a fase singola_ sono formattati in modo leggermente diverso rispetto ai flussi di lavoro che contengono più passaggi. Ad esempio, il nome dell'operazione esplicita viene rimosso. L'azione o l'operazione deve essere chiara in base al titolo del flusso di lavoro.



== Variabili di input

I flussi di lavoro sono progettati per essere il più generali possibile, pertanto possono essere utilizzati in qualsiasi ambiente ONTAP. Tenendo presente ciò, le chiamate API REST utilizzano variabili negli esempi curl e in altri input. Le chiamate API REST possono quindi essere facilmente adattate a diversi ambienti ONTAP.



=== Formato URL di base

È possibile accedere all'API REST ONTAP direttamente tramite curl o un linguaggio di programmazione. In questo caso, l'URL di base è diverso dall'URL utilizzato quando si accede alla documentazione online di ONTAP o a Gestione sistema.

Quando si accede direttamente all'API, è necessario aggiungere *api* al dominio o all'indirizzo IP. Ad esempio:

`https://ontap.demo-example.com/api`

Vedere link:../get-started/access_rest_api.html["Come accedere all'API REST di ONTAP"] per ulteriori informazioni.



=== Parametri di input comuni

Esistono diversi parametri di input comunemente utilizzati con la maggior parte delle chiamate API REST. Questi parametri in genere non vengono descritti nei singoli flussi di lavoro. È necessario acquisire familiarità con i parametri. Vedere link:../rest/input_variables.html["Variabili di input che controllano una richiesta API"] per ulteriori informazioni.

Se sono necessari parametri aggiuntivi per una specifica chiamata API REST, essi sono inclusi nella sezione *parametri di input aggiuntivi per l'esempio curl* per ogni flusso di lavoro.



=== Formato variabile

I valori ID e le altre variabili utilizzate con gli esempi di flusso di lavoro sono opachi e possono variare con ogni cluster ONTAP. Per migliorare la leggibilità degli esempi, non vengono utilizzati i valori effettivi. Vengono utilizzate invece le variabili. Questo approccio, basato su un formato coerente e su un insieme di nomi riservati, presenta diversi vantaggi, tra cui:

* I campioni Curl e JSON sono più leggibili e facili da capire.
* Poiché tutte le parole chiave utilizzano lo stesso formato, è possibile identificarle rapidamente.
* Non vi è alcuna esposizione di sicurezza perché i valori non possono essere copiati e riutilizzati.


Le variabili sono formattate per essere usate in un ambiente di shell Bash. Ogni variabile inizia con un simbolo del dollaro ed è racchiusa tra virgolette doppie secondo necessità. Questo li rende riconoscibili per Bash. Il maiuscolo viene utilizzato costantemente per i nomi.

Ecco alcune delle parole chiave variabili più comuni. Questo elenco non è esaustivo e, se necessario, vengono utilizzate variabili aggiuntive. Il loro significato dovrebbe essere ovvio in base al contesto.

[cols="25,15,60"]
|===
| Parola chiave | Tipo | Descrizione 


| $FQDN_IP | URL | Il nome di dominio o l'indirizzo IP pienamente qualificato della LIF di gestione ONTAP. 


| $CLUSTER_ID | Percorso | Valore UUIDv4 che identifica il cluster ONTAP in cui vengono eseguite le operazioni API. 


| $BASIC_AUTH | Intestazione | Stringa di credenziali utilizzata per l'autenticazione di base HTTP. 
|===


=== Esempi di input JSON

Alcune delle chiamate API REST, ad esempio quelle che utilizzano POST o PATCH, richiedono l'input JSON nel corpo della richiesta. Gli esempi di input JSON sono presentati separatamente dagli esempi di arricciatura per chiarezza. È possibile utilizzare gli esempi di input JSON con una delle tecniche descritte di seguito.

.Salva su file locale
È possibile copiare l'esempio di input JSON in un file e salvarlo localmente. Il comando curl si riferisce al file utilizzando il `--data` parametro con il valore che indica il nome del file con un `@` prefisso.

.Incollare nel terminale dopo l'esempio di arricciatura
Per prima cosa è necessario copiare e incollare l'esempio Curl in una shell terminale. Quindi modificare l'esempio per rimuovere completamente `--data` parametro alla fine e sostituirlo con l'attrezzo `--data-raw` parametro. Infine, copiare e incollare nell'esempio JSON in modo che segua il comando curl con il parametro aggiornato. È necessario utilizzare virgolette singole per racchiudere l'esempio di input JSON.



== Opzioni di autenticazione

Il metodo di autenticazione principale disponibile per l'API REST tramite ONTAP 9.13.1 è l'autenticazione di base.



=== Autenticazione di base HTTP

Quando si utilizza l'autenticazione di base, le credenziali utente devono essere incluse in ogni richiesta HTTP. Sono disponibili due opzioni per l'invio delle credenziali.

.Creare l'intestazione della richiesta HTTP
È possibile creare manualmente l'intestazione Authorization e includerla con le richieste HTTP. Questo può essere fatto quando si usa un comando curl nella CLI o un linguaggio di programmazione con il codice di automazione. I passaggi di alto livello includono:

. Concatenare i valori dell'utente e della password con due punti:
+
`admin:david123`

. Convertire l'intera stringa in base64:
+
`YWRtaW46ZGF2aWQxMjM=`

. Creare l'intestazione della richiesta:
+
`Authorization: Basic YWRtaW46ZGF2aWQxMjM=`



Gli esempi di curl del flusso di lavoro includono questa intestazione con la variabile *$BASIC_AUTH* che è necessario aggiornare prima dell'uso.

.Utilizzare un parametro Curl
Un'altra opzione quando si utilizza Curl è rimuovere l'intestazione Authorization e utilizzare invece il parametro curl *user*. Ad esempio:

`--user username:password`

È necessario sostituire le credenziali appropriate per l'ambiente in uso. Le credenziali non sono codificate in base64. Quando si esegue il comando curl con questo parametro, la stringa viene codificata e l'intestazione Authorization viene generata per l'utente.



== Uso degli esempi con Bash

Se si utilizzano direttamente gli esempi di curl del flusso di lavoro, è necessario aggiornare le variabili che contengono con i valori appropriati per l'ambiente in uso. Potete modificare manualmente gli esempi o affidarvi alla shell Bash per eseguire la sostituzione come descritto di seguito.


NOTE: Un vantaggio dell'utilizzo di Bash è che è possibile impostare i valori delle variabili una volta in una sessione di shell invece di una volta per comando curl.

.Fasi
. Aprire la shell Bash fornita con Linux o un sistema operativo simile.
. Impostare i valori delle variabili inclusi nell'esempio di arricciatura che si desidera eseguire. Ad esempio:
+
`CLUSTER_ID=ce559b75-4145-11ee-b51a-005056aee9fb`

. Copiare l'esempio di arricciatura dalla pagina del flusso di lavoro e incollarlo nel terminale della shell.
. Premere *INVIO* per effettuare le seguenti operazioni:
+
.. Sostituire i valori della variabile impostati
.. Eseguire il comando curl



