---
sidebar: sidebar 
permalink: workflows/wf_1_update_cluster_contact.html 
keywords: workflow 
summary: Questo flusso di lavoro aggiorna le informazioni di contatto del cluster. Poiché la richiesta viene elaborata in modo asincrono, illustra anche come determinare se il processo in background viene completato correttamente. 
---
= Workflow 1: Aggiornare il contatto del cluster e controllare lo stato del lavoro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questo flusso di lavoro aggiorna le informazioni di contatto del cluster. Poiché la richiesta viene elaborata in modo asincrono, illustra anche come determinare se il processo in background viene completato correttamente.



=== 1. Aggiornare le informazioni di contatto per il cluster

È possibile effettuare una chiamata API per aggiornare le informazioni di contatto. Poiché la richiesta viene eseguita in modo asincrono, è necessario confermare l'esito positivo del processo associato.

|===
| Categoria | Metodo HTTP | Percorso 


| Cluster | PATCH | /cluster 
|===
.Tipo di elaborazione
Asincrono

.Arricciatura
[source, curl]
----
curl -X PATCH -H 'Content-Type: application/json' -u admin:password -k -d @step01 'https://10.222.81.101/api/cluster'
{
  "contact": "support@company-demo.com"
}
----
.Output JSON
Viene restituito un oggetto lavoro con l'identificatore associato.

[source, json]
----
{ "job": {
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
  }
}
----


=== 2. Recuperare lo stato del lavoro

È necessario recuperare lo stato del lavoro per determinare se la richiesta asincrona è stata completata correttamente.

|===
| Categoria | Metodo HTTP | Percorso 


| Cluster | OTTIENI | /cluster/jobs/{uuid} 
|===
.Tipo di elaborazione
Sincrono

.Arricciatura
[source, curl]
----
curl -X GET -H 'Content-Type: application/json' -u admin:password -k 'https:// 10.222.81.101/api/cluster/jobs/*uuid*'
----
.Output
Viene restituito un oggetto di lavoro con lo stato e altri campi.

[source, json]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----