---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact 
summary: È possibile aggiornare le informazioni di contatto per un cluster. Poiché la richiesta viene elaborata in modo asincrono, è necessario anche determinare se il processo in background associato è stato completato correttamente. 
---
= Aggiornare il contatto del cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare le informazioni di contatto per un cluster. Poiché la richiesta viene elaborata in modo asincrono, è necessario anche determinare se il processo in background associato è stato completato correttamente.



== Passaggio 1: Aggiornare le informazioni di contatto del quadro strumenti

È possibile eseguire una chiamata API per aggiornare le informazioni di contatto del cluster.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| PATCH | /api/cluster 
|===
.Tipo di elaborazione
Asincrono

.Esempio di arricciamento
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Esempio di output JSON
Viene restituito un oggetto lavoro. È necessario salvare l'identificatore del lavoro per utilizzarlo nel passo successivo.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Passo 2: Recupero dello stato del lavoro

Eseguire il flusso di lavoro link:../workflows/wf_jobs_get_job.html["Recupera istanza lavoro"] e confermare `state` il valore è `success`.



== Fase 3: Confermare le informazioni di contatto del quadro strumenti

Eseguire il flusso di lavoro link:../workflows/wf_cls_get_cluster.html["Ottenere la configurazione del cluster"]. Impostare `fields` parametro query a. `contact`.
