---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact, job, job state 
summary: È possibile aggiornare le informazioni di contatto per un cluster. Poiché la richiesta viene elaborata in modo asincrono, questo flusso di lavoro illustra anche come determinare se il processo in background associato è stato completato correttamente. 
---
= Aggiornare il contatto del cluster e confermare lo stato del lavoro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare le informazioni di contatto per un cluster. Poiché la richiesta viene elaborata in modo asincrono, questo flusso di lavoro illustra anche come determinare se il processo in background associato è stato completato correttamente.



== Passaggio 1: Aggiornare le informazioni di contatto del quadro strumenti

È possibile eseguire una chiamata API per aggiornare le informazioni di contatto del cluster.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| PATCH | /cluster 
|===
.Tipo di elaborazione
Asincrono

.Esempio di arricciamento
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Esempio di output JSON
L'oggetto lavoro viene restituito. È necessario salvare l'identificatore del processo per utilizzarlo nella fase successiva come variabile $JOB_ID.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Passo 2: Recupero dello stato del lavoro

È necessario recuperare lo stato del processo per determinare se la richiesta asincrona è stata completata correttamente.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /cluster/jobs/{uuid} 
|===
.Tipo di elaborazione
Sincrono

.Esempio di arricciamento
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
Il valore di stato e gli altri campi sono inclusi nell'oggetto lavoro restituito.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----


== Fase 3: Confermare le informazioni di contatto del quadro strumenti

Eseguire il flusso di lavoro link:../workflows/wf_get_cluster.html["Ottenere la configurazione del cluster"]. Impostare `fields` parametro query a. `contact`.
