---
sidebar: sidebar 
permalink: workflows/wf_ems_list_log_events.html 
keywords: support, ems, event management system, get events, get notifications, retrieve events 
summary: È possibile recuperare tutti i messaggi di notifica degli eventi o quelli con caratteristiche specifiche. 
---
= Elencare gli eventi del registro EMS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile recuperare tutti i messaggi di notifica degli eventi o solo quelli con caratteristiche specifiche.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/support/ems/events 
|===
.Tipo di elaborazione
Sincrono

.Parametri di input aggiuntivi per gli esempi Curl
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| campi | Query | No | Utilizzato per richiedere campi specifici da includere nella risposta. 


| max_records | Query | No | Può essere utilizzato per limitare il numero di record restituiti in una singola richiesta. 


| log_message | Query | No | Consente di cercare un valore di testo specifico e di restituire solo i messaggi corrispondenti. 


| message.severity | Query | No | Limitare i messaggi restituiti a quelli con un livello di gravità specifico, ad esempio `alert`. 
|===
.Esempio Curl: Restituisce l'ultimo messaggio e il valore del nome
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/support/ems/events?fields=message.name&max_records=1" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio Curl: Consente di restituire un messaggio contenente testo e gravità specifici
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/support/ems/events?log_message=*disk*&message.severity=alert" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
[listing]
----
{
  "records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----