---
sidebar: sidebar 
permalink: workflows/wf_get_cluster.html 
keywords: workflow, get cluster, cluster configuration 
summary: È possibile recuperare la configurazione per un cluster ONTAP che include campi specifici. Questa operazione può essere eseguita durante la valutazione dello stato del cluster o prima di aggiornare la configurazione. 
---
= Ottenere la configurazione del cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile recuperare la configurazione per un cluster ONTAP che include campi specifici. Questa operazione può essere eseguita durante la valutazione dello stato del cluster o prima di aggiornare la configurazione.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | OTTIENI 


| OTTIENI | /cluster 
|===
.Parametri di input aggiuntivi per esempi di arricciatura
Oltre ai parametri comuni a tutte le chiamate REST API, nell'esempio curl in questo passo vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| campi | Query | No | Selezionare i valori che si desidera restituire. Alcuni esempi sono `contact` e. `version`. 
|===
.Esempio Curl: Recupero delle informazioni di contatto del cluster
In questo esempio viene illustrato come recuperare un singolo campo. Per ottenere l'intero oggetto e la configurazione del cluster, è necessario rimuovere l' `fields` parametro di query.

[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster?fields=contact" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
[listing]
----
{
  "contact": "support@company-demo.com"
}
----