---
sidebar: sidebar 
permalink: workflows/wf_jobs_get_job.html 
keywords: workflow, job, job state 
summary: 'È possibile recuperare l"istanza di un processo ONTAP specifico. In genere, questa operazione viene eseguita per determinare se il processo e l"operazione associata sono stati completati correttamente.' 
---
= Ottenere l'istanza di lavoro utilizzando l'API REST di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile recuperare l'istanza di un processo ONTAP specifico. In genere, questa operazione viene eseguita per determinare se il processo e l'operazione associata sono stati completati correttamente.


NOTE: È necessario l'UUID dell'oggetto lavoro, che in genere viene fornito dopo l'emissione di una richiesta asincrona. Inoltre, rivedere link:../rest/asynchronous_processing.html["Elaborazione asincrona utilizzando l'oggetto Job"] Prima di lavorare con i job interni di ONTAP.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/cluster/jobs/{uuid} 
|===
.Tipo di elaborazione
Sincrono

.Parametri di input aggiuntivi per gli esempi Curl
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| $JOB_ID | Percorso | Sì | Necessario per identificare il lavoro richiesto. 
|===
.Esempio di arricciamento
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
Il valore di stato e gli altri campi sono inclusi nell'oggetto lavoro restituito. Il lavoro in questo esempio è stato eseguito come parte dell'aggiornamento di un cluster ONTAP.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----