---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_apply_permissions.html 
keywords: nas, file security, sacl, dacl, permissions, apply permissions 
summary: È possibile applicare un nuovo descrittore di protezione a un file o una cartella specifici. 
---
= Applicare nuove autorizzazioni a un file
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile applicare un nuovo descrittore di protezione a un file o una cartella specifici.



== Passaggio 1: Applicare le nuove autorizzazioni

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /api/protocolli/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo di elaborazione
Asincrono

.Parametri di input aggiuntivi per esempi di arricciatura
Oltre ai parametri comuni a tutte le chiamate REST API, nell'esempio curl in questo passo vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| $SVM_ID | Percorso | Sì | UUUID della SVM che contiene il file. 


| $PERCORSO_FILE | Percorso | Sì | Questo è il percorso del file o della cartella. 
|===
.Esempio di arricciamento
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}'
----
.Esempio di output JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Passo 2: Recupero dello stato del lavoro

Eseguire il flusso di lavoro link:../workflows/wf_jobs_get_job.html["Recupera istanza lavoro"] e confermare `state` il valore è `success`.
