---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_get_permissions.html 
keywords: nas, file security, effective permissions 
summary: È possibile recuperare le autorizzazioni effettive correnti per un file o una cartella specifici. 
---
= Ottenere le autorizzazioni effettive per un file
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile recuperare le autorizzazioni effettive correnti per un file o una cartella specifici.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/protocolli/file-security/effective-permissions/{svm.uuid}/{path} 
|===
.Tipo di elaborazione
Sincrono

.Parametri di input aggiuntivi per esempi di arricciatura
Oltre ai parametri comuni a tutte le chiamate REST API, nell'esempio curl in questo passo vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| $SVM_ID | Percorso | Sì | UUUID della SVM che contiene il file. 


| $PERCORSO_FILE | Percorso | Sì | Questo è il percorso del file o della cartella. 
|===
.Esempio di arricciamento
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/protocols/file-security/effective-permissions/$SVM_ID/$FILE_PATH" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
[listing]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----