---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_delete_ace.html 
keywords: nas, file security, access control entry, ace, delete ace 
summary: 'È possibile eliminare una voce di controllo dell"accesso esistente (ACE) da un file o una cartella specifici. La modifica si propaga a qualsiasi oggetto figlio.' 
---
= Eliminare una voce di controllo dell'accesso utilizzando l'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile eliminare una voce ACE (Access Control Entry) esistente da un file o una cartella specifici. La modifica si propaga a qualsiasi oggetto figlio.



== Passaggio 1: Eliminare l'ACE

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| ELIMINARE | /api/protocolli/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo di elaborazione
Asincrono

.Parametri di input aggiuntivi per esempi di arricciatura
Oltre ai parametri comuni a tutte le chiamate REST API, nell'esempio curl in questo passo vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| $SVM_ID | Percorso | Sì | UUUID della SVM che contiene il file. 


| $PERCORSO_FILE | Percorso | Sì | Questo è il percorso del file o della cartella. 
|===
.Esempio di arricciamento
[source, curl]
----
curl --request DELETE --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}'
----
.Esempio di output JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Passo 2: Recupero dello stato del lavoro

Eseguire il flusso di lavoro link:../workflows/wf_jobs_get_job.html["Recupera istanza lavoro"] e confermare `state` il valore è `success`.
