---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_update_sd.html 
keywords: nas, file security, security descriptor, sd, update security descriptor 
summary: È possibile aggiornare un descrittore di protezione specifico a un file o una cartella specifici, inclusi i flag del proprietario, del gruppo o del controllo principale. 
---
= Aggiornare le informazioni del descrittore di protezione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare un descrittore di protezione specifico a un file o una cartella specifici, inclusi i flag del proprietario, del gruppo o del controllo principale.



== Passaggio 1: Aggiornare il descrittore di protezione

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| PATCH | /api/protocolli/file-security/permissions/{svm.uuid}/{path} 
|===
.Tipo di elaborazione
Asincrono

.Parametri di input aggiuntivi per esempi di arricciatura
Oltre ai parametri comuni a tutte le chiamate REST API, nell'esempio curl in questo passo vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| $SVM_ID | Percorso | Sì | UUUID della SVM che contiene il file. 


| $PERCORSO_FILE | Percorso | Sì | Questo è il percorso del file o della cartella. 
|===
.Esempio di arricciamento
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'
----
.Esempio di output JSON
[listing]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Passo 2: Recupero dello stato del lavoro

Eseguire il flusso di lavoro link:../workflows/wf_jobs_get_job.html["Recupera istanza lavoro"] e confermare `state` il valore è `success`.
