---
sidebar: sidebar 
permalink: workflows/wf_stor_list_aggrs.html 
keywords: workflow, storage, aggregates, list aggregates 
summary:  
---
= Elenca gli aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile recuperare un elenco di aggregati nel cluster. Questa operazione può essere eseguita per la valutazione dell'utilizzo e delle prestazioni.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/storage/dischi 
|===
.Tipo di elaborazione
Sincrono

.Parametri di input aggiuntivi per gli esempi Curl
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| node.name | Query | No | Può essere utilizzato per identificare il nodo a cui è collegato ciascun aggregato. 
|===
.Esempio di curl: Restituisce tutti gli aggregati con i valori di configurazione predefiniti
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio Curl: Restituisce tutti gli aggregati con un valore di configurazione specifico
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates?fields=node.name" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "uuid": "760d8137-fc59-47da-906a-cc28db0a1c1b",
      "name": "sti214_vsim_sr027o_aggr1",
      "node": {
        "name": "sti214-vsim-sr027o"
      },
      "_links": {
        "self": {
          "href": "/api/storage/aggregates/760d8137-fc59-47da-906a-cc28db0a1c1b"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/storage/aggregates?fields=node.name"
    }
  }
}
----
====