---
sidebar: sidebar 
permalink: workflows/wf_stor_list_disks.html 
keywords: workflow, storage, disks, list disks 
summary: È possibile recuperare un elenco di dischi nel cluster. Questa operazione può essere eseguita per individuare una o più unità di riserva da utilizzare come parte della creazione di un aggregato. 
---
= Elencare i dischi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile recuperare un elenco di dischi nel cluster. Questa operazione può essere eseguita per individuare una o più unità di riserva da utilizzare come parte della creazione di un aggregato.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/storage/dischi 
|===
.Tipo di elaborazione
Sincrono

.Parametri di input aggiuntivi per gli esempi Curl
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| stato | Query | No | Consentono di identificare i dischi di riserva disponibili per i nuovi aggregati. 
|===
.Esempio di arricciatura: Restituire tutti i dischi
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di arricciatura: Restituire i dischi di ricambio
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks?state=spare" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Esempio di output JSON
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "name": "NET-1.20",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.20"
        }
      }
    },
    {
      "name": "NET-1.12",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.12"
        }
      }
    },
    {
      "name": "NET-1.7",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.7"
        }
      }
    }
  ],
  "num_records": 3,
  "_links": {
    "self": {
      "href": "/api/storage/disks?state=spare"
    }
  }
}
----
====