---
sidebar: sidebar 
permalink: python/overview_pcl.html 
keywords: overview, python client library, pcl 
summary: 'La libreria client di NetApp ONTAP Python è un pacchetto che è possibile installare e utilizzare per scrivere script che accedono all"API REST di ONTAP. Utilizzando la libreria client di Python, è possibile sviluppare rapidamente un codice affidabile per supportare l"automazione delle implementazioni ONTAP.' 
---
= Panoramica della libreria client Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La libreria client di NetApp ONTAP Python è un pacchetto che è possibile installare e utilizzare per scrivere script che accedono all'API REST di ONTAP. Fornisce supporto per diversi servizi sottostanti, tra cui gestione della connessione, elaborazione asincrona, gestione delle eccezioni e messaggi di errore. Utilizzando la libreria client di Python, è possibile sviluppare rapidamente un codice affidabile per supportare l'automazione delle implementazioni ONTAP.


NOTE: NetApp gestisce un repository GitHub contenente esempi di codice e altre informazioni utili. È possibile accedere alla cartella _esempi_ per accedere agli esempi utilizzando la libreria client Python.

.Informazioni correlate
* https://github.com/NetApp/ontap-rest-python["Repository GitHub di ONTAP REST Python"^]
* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Esempi di librerie di client Python REST ONTAP"^]

