---
sidebar: sidebar 
permalink: python/prepare_pcl.html 
keywords: python client library, prepare, pcl 
summary: 'Si consiglia di preparare l"ambiente di runtime locale prima di utilizzare la libreria client Python.' 
---
= Preparatevi a utilizzare la libreria client Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si consiglia di preparare l'ambiente di runtime locale prima di utilizzare la libreria client Python.

.Nome e versione del pacchetto
Il nome del pacchetto di librerie client Python è *netapp-ontap*. La versione associata al pacchetto è una combinazione dei numeri di versione principali e minori di ONTAP da cui è stata generata la libreria, insieme a una versione minore per il client all'interno della release di ONTAP. Ad esempio, i numeri di versione validi includono: 9.6.1, 9.6.2 e 9.7.1.

.Installazione
È necessario utilizzare pip per installare il pacchetto netapp_ontap dal sito Web Python Package Index (PyPi).

.Pacchetti e documentazione di ONTAP
Ogni versione di ONTAP che inizia con 9,6 ha un pacchetto PyPI e la relativa documentazione. Vedere link:../python/packages.html["Pacchetti e documentazione"] per ulteriori informazioni. I requisiti di installazione sono inclusi in ogni pacchetto e includono diverse versioni delle seguenti:

* python
* richieste
* richieste-cintura degli attrezzi
* marshmallow

