---
sidebar: sidebar 
permalink: get-started/first_call.html 
keywords: first REST API call, test REST API 
summary: 'Puoi eseguire un comando curl per iniziare a utilizzare l"API REST di ONTAP e confermarne la disponibilità.' 
---
= La prima chiamata ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puoi eseguire un semplice comando curl per iniziare a utilizzare l'API REST di ONTAP e confermarne la disponibilità.

.Prima di iniziare
Oltre alla disponibilità dell'utilità Curl sulla workstation, è necessario disporre di quanto segue:

* Indirizzo IP o FQDN della LIF di gestione cluster ONTAP
* Credenziali ONTAP per un account con autorizzazione ad accedere all'API REST ONTAP



NOTE: Se le credenziali includono caratteri speciali, è necessario formattarli in un modo accettabile per arricciarsi in base alla shell che si sta utilizzando. Ad esempio, è possibile inserire una barra rovesciata prima di ogni carattere speciale o racchiudere l'intera stringa di credenziali tra virgolette doppie.

.Fasi
. Nell'interfaccia della riga di comando della workstation locale, immettere il seguente comando:
+
[source, curl]
----
curl --request GET \
"https://$FQDN_IP/api/cluster?fields=version" \
--user username:password
----
+
*Esempio*

+
`curl --request GET "https://10.29.186.132/api/cluster?fields=version" --user admin:david123`



.Al termine
Le informazioni sulla versione di ONTAP vengono visualizzate in formato JSON.
