---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog 
summary: 'Sono disponibili diverse opzioni per automatizzare la distribuzione e l"amministrazione dei vostri sistemi storage ONTAP.' 
---
= Comprendere le opzioni di automazione di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sono disponibili diverse opzioni per automatizzare la distribuzione e l'amministrazione dei vostri sistemi storage ONTAP.



== API REST di ONTAP

A partire da ONTAP 9.6, ONTAP include una solida API REST che fornisce le basi per automatizzare la distribuzione e l'amministrazione dei sistemi di storage.  Da allora la REST API ha continuato ad espandersi e maturare.  Ora rappresenta l'opzione preferita e strategica per automatizzare l'amministrazione delle distribuzioni ONTAP .

.Accesso all'API REST in modo nativo
È possibile accedere direttamente all'API REST di ONTAP utilizzando qualsiasi linguaggio di programmazione che supporti un client REST. Le lingue più diffuse includono Python, PowerShell e Java.

.Migrazione del codice ONTAPI legacy per utilizzare REST
L'API ONTAPI (Zephyr API o ZAPI) è il set originale di chiamate proprietarie incluse nel software NetApp ONTAP per supportare l'automazione delle attività di amministrazione e gestione dell'archiviazione dei dati.  L'API fa parte dellink:../sw-tools/learn-about-nmsdk.html["SDK per la gestibilità di NetApp"] .  Se disponi di codice esistente che utilizza l'API ONTAPI, dovresti pianificare la migrazione all'API REST ONTAP per sfruttare il set di funzionalità ampliato disponibile con l'API REST.  NetApp fornisce supporto per la conversione del codice in modo da utilizzare la più recente API REST ONTAP . Vedere link:../migrate/migration-considerations.html["Migrare da ONTAPI all'API REST"] per maggiori informazioni.



== Kit di strumenti software client

NetApp offre toolkit per i client che astraggono l'API REST di ONTAP e semplificano la creazione del codice di automazione. È necessario scegliere una lingua appropriata per il linguaggio e l'ambiente di sviluppo.

.Libreria client Python
La libreria client Python è un pacchetto che puoi utilizzare per scrivere script per accedere all'API REST di ONTAP. Fornisce supporto per diversi servizi sottostanti, tra cui gestione della connessione, elaborazione delle richieste asincrone e gestione delle eccezioni. Utilizzando la libreria client Python, puoi sviluppare rapidamente un codice solido per supportare i tuoi obiettivi di automazione ONTAP. Per ulteriori informazioni, vedere link:../python/learn-about-pcl.html["Libreria client Python"] .

.Toolkit PowerShell
Puoi utilizzare il NetApp.ONTAP PowerShell Toolkit per automatizzare l'amministrazione di un cluster ONTAP da un host Windows. Per ulteriori informazioni, vedere link:../pstk/learn-about-pstk.html["Ulteriori informazioni sul toolkit PowerShell di NetApp"] .



== Framework di automazione

È possibile creare e distribuire codice di automazione utilizzando uno dei numerosi framework.

.Ansible
Ansible è uno strumento software open-source che supporta il provisioning, la gestione della configurazione e l'implementazione delle applicazioni. Dal suo rilascio e dalla successiva acquisizione da parte di RedHat, ha continuato a crescere in popolarità. NetApp offre moduli certificati Ansible che i clienti possono utilizzare per automatizzare l'amministrazione dei propri sistemi storage ONTAP. Vedere link:../additional/learn_more.html["Scopri di più"] e. https://www.netapp.com/devops-solutions/ansible/["Soluzioni NetApp Ansible DevOps"^] per ulteriori informazioni.

.Catalogo di automazione BlueXP
NetApp https://console.bluexp.netapp.com/automationCatalog/["Catalogo di automazione BlueXP"^] È disponibile tramite l'interfaccia utente web BlueXP. Il catalogo fornisce accesso a soluzioni predisposte per l'installazione automatica e l'integrazione di ONTAP con altri prodotti. Vedere https://docs.netapp.com/us-en/netapp-automation/["Automazione di NetApp"^] per documentazione e ulteriori informazioni.
