---
sidebar: sidebar 
permalink: rest/rbac_wf_create_user.html 
keywords: rbac, workflow, create role, create user 
summary: È possibile utilizzare il flusso di lavoro descritto di seguito per creare un utente con un ruolo REST associato. Prima di esaminare il flusso di lavoro, dovresti avere familiarità con le fasi generali di preparazione. 
---
= Creare un utente con un ruolo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il flusso di lavoro descritto di seguito per creare un utente con un ruolo REST associato. Prima di esaminare il flusso di lavoro, dovresti avere familiarità con le fasi generali di preparazione.



== Prepararsi a creare un utente ONTAP con un ruolo assegnato

Prima di creare un ruolo e assegnarlo a un account utente di ONTAP, è necessario prima di tutto prepararsi esaminando i requisiti e le opzioni di sicurezza principali.

.Quale versione di ONTAP stai utilizzando?
La release ONTAP determina quali endpoint REST e le funzionalità RBAC sono disponibili.

.Identificare le risorse protette e l'ambito
È necessario identificare le risorse o i comandi da proteggere e l'ambito (cluster o SVM).

.Quale accesso deve avere l'utente?
Dopo aver identificato le risorse e l'ambito, è necessario determinare il livello di accesso da concedere.

.In che modo gli utenti accedono a ONTAP?
L'utente può accedere a ONTAP tramite l'API REST o CLI o entrambi.

.Uno dei ruoli integrati è sufficiente o è necessario un ruolo personalizzato?
È più conveniente utilizzare un ruolo integrato esistente, ma è possibile creare un nuovo ruolo personalizzato, se necessario.

.Che tipo di ruolo è necessario?
In base ai requisiti di sicurezza e all'accesso a ONTAP, è necessario scegliere se creare un ruolo REST o tradizionale.



== Creare un utente con un ruolo personalizzato

Il flusso di lavoro descritto di seguito include i passaggi tipici necessari per creare un ruolo REST personalizzato e associarlo a un nuovo account utente. Sia l'utente che il ruolo hanno un ambito SVM e sono associati a un SVM di dati specifico.


NOTE: Il flusso di lavoro serve a illustrare il processo completo. Alcuni passaggi potrebbero essere facoltativi o richiedere modifiche in base all'ambiente in uso.



=== 1. Elencare le SVM dei dati nel cluster

Eseguire la seguente chiamata API REST per elencare le SVM nel cluster. L'UUID e il nome di ogni SVM vengono forniti nell'output.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/svm/svm 
|===
.esempio di arricciamento
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms?order_by=name' -u admin:password -k --header 'Accept: */*'
----
.Al termine
Selezionare la SVM desiderata dall'elenco in cui creare il nuovo utente e il nuovo ruolo.



=== 2. Elencare gli utenti definiti per SVM

Eseguire la seguente chiamata API REST per elencare gli utenti definiti nella SVM selezionata. È possibile identificare la SVM attraverso il parametro owner.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/security/accounts 
|===
.esempio di arricciamento
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/accounts/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
.Al termine
In base agli utenti già definiti nella SVM, scegliere un nome univoco per il nuovo utente.



=== 3. Elencare i ruoli DI RIPOSO definiti per la SVM

Eseguire la seguente chiamata API REST per elencare i ruoli definiti nella SVM selezionata. È possibile identificare la SVM attraverso il parametro owner.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /api/security/ruoli 
|===
.esempio di arricciamento
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
.Al termine
In base ai ruoli già definiti nella SVM, scegliere un nome univoco per il nuovo ruolo.



=== 4. Creare un ruolo REST personalizzato

Eseguire la seguente chiamata API REST per creare un ruolo REST personalizzato nella SVM. Il ruolo inizialmente dispone di un solo privilegio che stabilisce un accesso predefinito di *nessuno* in modo che tutti gli accessi siano negati.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /api/security/ruoli 
|===
.Esempio di input JSON
[source, json]
----
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "752d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}
----
.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
.Al termine
Eseguire di nuovo il passaggio 3 per visualizzare il nuovo ruolo. È inoltre possibile visualizzare i ruoli nella CLI di ONTAP.



=== 5. Aggiornare il ruolo aggiungendo ulteriori privilegi

Eseguire la seguente chiamata API REST per modificare il ruolo aggiungendo i privilegi necessari.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /api/security/roles/{owner.uuid}/{name}/privileges 
|===
.Esempio di input JSON
[source, json]
----
{
  "path": "/api/storage/volumes", "access": "readonly"}
}
----
.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles/752d96be-f17c-11ec-9d19-005056bbad91/dprole1/privileges' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
.Al termine
Eseguire di nuovo il passaggio 3 per visualizzare il nuovo ruolo. È inoltre possibile visualizzare i ruoli nella CLI di ONTAP.



=== 6. Creare un utente

Eseguire la seguente chiamata API REST per creare un account utente. Il ruolo `dprole1` creato in precedenza è associato al nuovo utente.


TIP: È possibile includere l'utente senza un ruolo. In questo caso, è necessario modificare l'utente per assegnare un ruolo.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /api/security/accounts 
|===
.Esempio di input JSON
[source, json]
----
{
  "owner": {"uuid":"daf84055-248f-11ed-a23d-005056ac4fe6"},
  "name": "david",
  "applications": [
      {"application":"ssh",
       "authentication_methods":["password"],
       "second_authentication_method":"none"}
  ],
  "role":"dprole1",
  "password":"netapp123"
}
----
.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/accounts' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
.Al termine
È possibile accedere all'interfaccia di gestione SVM utilizzando le credenziali del nuovo utente.
