---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords: rbac, role definitions, samples 
summary: 'La funzionalità RBAC di ONTAP può essere utilizzata in diversi modi, a seconda dell"ambiente in uso. Di seguito vengono presentati alcuni scenari comuni. In ogni caso, l"attenzione si concentra su un obiettivo amministrativo e di sicurezza specifico con un esempio della definizione del ruolo corrispondente.' 
---
= Definizioni di ruoli di esempio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La funzionalità RBAC di ONTAP può essere utilizzata in diversi modi, a seconda dell'ambiente in uso. Di seguito vengono presentati alcuni scenari comuni. In ogni caso, l'attenzione si concentra su un obiettivo amministrativo e di sicurezza specifico con un esempio della definizione del ruolo corrispondente.


NOTE: Tutti gli esempi creano e modificano i ruoli utilizzando `/api/security/roles` E gli endpoint REST derivati. Per maggiore chiarezza, ciascun comando curl si riferisce a un file di input JSON separato.



== Limitare l'accesso alle operazioni dei volumi SVM

È possibile limitare l'amministrazione dei volumi di storage all'interno di una SVM. Nell'esempio riportato di seguito viene illustrato un ruolo che viene creato e quindi eventualmente aggiornato.



=== Creare il ruolo iniziale

Viene creato un ruolo tradizionale per consentire inizialmente l'accesso a tutte le principali funzioni di amministrazione dei volumi, ad eccezione della clonazione. Il ruolo presentato di seguito è definito con le seguenti caratteristiche specifiche:

* È in grado di eseguire tutte le operazioni dei volumi CRUD, tra cui Get, create, Modify ed Delete
* Impossibile creare un clone del volume


.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== Aggiornare il ruolo

È possibile modificare lo stesso ruolo per consentire all'utente di creare anche un clone del volume.

.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== Amministrazione della protezione dei dati

In alcune situazioni, è possibile fornire a un utente funzionalità di protezione dei dati limitate. Il ruolo tradizionale presentato di seguito è definito con le seguenti caratteristiche:

* Possibilità di creare ed eliminare snapshot e aggiornare le relazioni di SnapMirror
* Impossibile creare o modificare oggetti di livello superiore come volumi o SVM


.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== Generazione di report ONTAP

È possibile creare un ruolo REST per fornire agli utenti la possibilità di generare report ONTAP. Il ruolo presentato di seguito è definito con le seguenti caratteristiche:

* In grado di recuperare tutte le informazioni relative a capacità e performance (ad esempio volume, qtree, LUN, aggregati, nodo, E relazioni SnapMirror)
* Impossibile creare o modificare oggetti di livello superiore (ad esempio volumi o SVM)


.esempio di arricciamento
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----