---
sidebar: sidebar 
permalink: rest/users_ontapi_api_ontap_cli.html 
keywords: snapdiff, migrating to rest 
summary: 'ONTAPI è un insieme di chiamate API fornite tramite l"SDK per la gestione della rete che può essere utilizzato per amministrare i sistemi di storage ONTAP. Esistono differenze tra le chiamate REST API e ONTAPI, nonché tra REST API e ONTAP CLI.' 
---
= Utenti di ONTAPI API e CLI ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPI è un insieme di chiamate API fornite tramite l'SDK per la gestione della rete che può essere utilizzato per amministrare i sistemi di storage ONTAP. Esistono differenze tra le chiamate REST API e ONTAPI, nonché tra REST API e ONTAP CLI. È necessario comprendere queste differenze prima di utilizzare L'API REST in un ambiente di produzione.



== Differenze di progettazione generali

L'API REST di ONTAP e l'interfaccia della riga di comando hanno un design fondamentalmente diverso. I comandi e i parametri CLI non vengono mappati direttamente alle chiamate API REST. E anche laddove vi sia una somiglianza, i dettagli dei parametri di input possono essere diversi. Ad esempio, le unità numeriche possono essere specificate in byte o utilizzando un suffisso (ad esempio KB). Dovresti rivedere link:input_variables.html["Variabili di input che controllano una richiesta API"] così come il link:../reference/api_reference.html["Riferimento API"] per ulteriori informazioni.



== SVM di dati esposti attraverso l'API REST

ONTAP supporta diversi tipi di macchine virtuali per lo storage (SVM). Tuttavia, solo le SVM dei dati vengono esposte direttamente attraverso l'API REST di ONTAP. Le informazioni di configurazione che descrivono il cluster e i nodi sono disponibili attraverso l'API REST, tuttavia il cluster e i nodi non vengono trattati come SVM separate.



== Migrazione da ONTAPI a REST

L'API REST è la scelta principale e strategica per l'automazione dell'amministrazione del sistema ONTAP. Se si utilizza l'API ONTAPI, è consigliabile eseguire la migrazione all'API REST. NetApp fornisce la documentazione di mappatura per agevolare la migrazione da ONTAPI a REST. Vedere link:../migrate/mapping.html["ONTAPI per il mapping API REST"] per ulteriori informazioni.



== Modifiche alla disponibilità di SnapDiff in ONTAPI

A partire da ONTAP 9.10.1, le chiamate SnapDiff v1 e v2 ONTAPI non possono essere richiamate. Qualsiasi applicazione di terze parti che richiama le chiamate SnapDiff v1 o v2 ONTAPI non funzionerà a partire da ONTAP 9.10.1. Gli utenti di ONTAP devono verificare che l'applicazione di backup supporti le chiamate REST SnapDiff v3 prima di eseguire l'aggiornamento a ONTAP 9.10.1.

La disponibilità delle API SnapDiff nelle release di ONTAP viene definita come segue:

* ONTAP 9.7 e versioni precedenti: v1 e v2 (solo ONTAPI)
* ONTAP 9.8 – 9.9.1: v1, v2 e v3 (ONTAPI e REST API)
* ONTAP 9.10.1: Solo v3 (solo API REST)


Per ulteriori informazioni, consultare https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note di rilascio di ONTAP"^].

.Informazioni correlate
* link:../rest/input_variables.html["Variabili di input che controllano una richiesta API"]
* link:../migrate/mapping.html["ONTAPI per il mapping API REST"]

