---
permalink: manage/dacl-sacl-rest-api.html 
sidebar: sidebar 
keywords: dacl, sacl, permissions, file, api, access, vserver, control, list, access control list, access control 
summary: 'È possibile gestire le autorizzazioni dei file DACL e SACL utilizzando l"API REST di ONTAP.' 
---
= Gestire le autorizzazioni dei file DACL e SACL con l'API REST di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilizza gli elenchi di controllo di accesso di sistema (SACL) e gli elenchi di controllo di accesso discrezionali (DACL) per assegnare le autorizzazioni agli oggetti file. A partire da ONTAP 9.9.1, l'API REST di ONTAP include gli endpoint per assegnare le autorizzazioni SACL e DACL per i file e automatizzare le autorizzazioni di sicurezza dei file. Ulteriori informazioni sulle opzioni per l'automazione delle autorizzazioni SACL e DACL prima di ONTAP 9.9.1 https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["qui"^]).

A partire da ONTAP 9.9.1, è possibile utilizzare una singola chiamata API REST al posto di più comandi CLI o chiamate ONTAPI. Gli esempi seguenti mostrano come utilizzare l'API REST di ONTAP per lavorare con le autorizzazioni dei file. In ogni esempio, assicurarsi di fornire i valori per le informazioni tra parentesi <> dove indicato.

È anche possibile fare riferimento a un esempio https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Script Python"^] Ciò dimostra come automatizzare una serie di attività correlate a SACL e DACL.



== Visualizzare le autorizzazioni effettive

Utilizzando il `GET /protocols/file-security/effective-permissions/` API Call, è possibile recuperare le autorizzazioni correnti per un file o una directory specifica.

.Richiesta di esempio:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/effective-permissions/cf5f271a-1beb-11ea-8fad-005056bb645e/administrator/windows/%2F?share.name=sh1&return_records=true'
----
.Esempio di risposta
[source, json]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----


== Visualizzare tutte le informazioni di controllo

Utilizzando il `GET /protocols/file-security/permissions/` API Call, è possibile recuperare tutte le informazioni di controllo per un file o una directory specifica.

.Richiesta di esempio:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----
.Esempio di risposta
[source, json]
----
{
  "svm": {
    "uuid": "9479099d-5b9f-11eb-9c4e-0050568e8682",
    "name": "vs1"
  },
  "path": "/parent",
  "owner": "BUILTIN\\Administrators",
  "group": "BUILTIN\\Administrators",
  "control_flags": "0x8014",
  "acls": [
    {
      "user": "BUILTIN\\Administrators",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    },
    {
      "user": "BUILTIN\\Users",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    }
  ],
  "inode": 64,
  "security_style": "mixed",
  "effective_style": "ntfs",
  "dos_attributes": "10",
  "text_dos_attr": "----D---",
  "user_id": "0",
  "group_id": "0",
  "mode_bits": 777,
  "text_mode_bits": "rwxrwxrwx"
}

----


== Applicare nuove autorizzazioni

Utilizzando il `POST /protocols/file-security/permissions/` API Call, è possibile applicare un nuovo descrittore di sicurezza a un file o a una directory.

.Richiesta di esempio
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Esempio di risposta
[source, json]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Aggiornare le informazioni del descrittore di protezione

Utilizzando il `PATCH /protocols/file-security/permissions/` API Call, è possibile aggiornare informazioni specifiche sul descrittore di sicurezza per un file o una directory, come il proprietario primario, il gruppo o i flag di controllo.

.Richiesta di esempio
[source, curl]
----
curl -u admin:<PASSWORD> -X PATCH -d '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Esempio di risposta
[source, json]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Eliminazione di una voce di controllo di accesso SACL/DACL (Access Control Entry) esistente

Utilizzando il `DELETE /protocols/file-security/permissions/` API Call, è possibile eliminare un ACE esistente da un file per directory. Questo esempio propaga la modifica a qualsiasi oggetto figlio.

.Richiesta di esempio
[source, curl]
----
curl -u admin:<PASSWORD> -X DELETE -d '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent/acl/himanshu?return_timeout=0'
----
.Esempio di risposta
[source, json]
----
{
  "job": {
    "uuid": "e5683b61-5bbf-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/e5683b61-5bbf-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== API REST ONTAP e comandi CLI ONTAP

L'API REST di ONTAP consente di automatizzare i flussi di lavoro con meno comandi rispetto all'interfaccia CLI di ONTAP per molte attività. Ad esempio, è possibile utilizzare un singolo metodo POST API per modificare un descrittore di protezione per un file, invece di utilizzare più comandi CLI. La seguente tabella mostra i comandi CLI necessari per completare le attività di autorizzazione del file system più comuni rispetto alle corrispondenti chiamate API REST:

|===
| API REST di ONTAP | CLI ONTAP 


| `GET /protocols/file-security/effective-permissions/`  a| 
`vserver security file-directory show-effective-permissions`



| `POST /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs create`
. `vserver security file-directory ntfs dacl add`
. `vserver security file-directory ntfs sacl add`
. `vserver security file-directory policy create`
. `vserver security file-directory policy task add`
. `vserver security file-directory apply`




| `PATCH /protocols/file-security/permissions/`  a| 
`vserver security file-directory ntfs modify`



| `DELETE /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs dacl remove`
. `vserver security file-directory ntfs sacl remove`


|===


== Informazioni correlate

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["ONTAP REST API DACL/SACL permissions esempio di script Python"^]
* https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis/["Gestione semplificata delle autorizzazioni di sicurezza dei file con le API REST di ONTAP"^]
* https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Utilizzo del pass-through CLI privato con l'API REST ONTAP (per le versioni di ONTAP precedenti alla versione 9.9.1)"^]

