---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: 'È possibile gestire la configurazione EMS di ONTAP utilizzando l"API REST.' 
---
= Gestisci le notifiche degli eventi EMS con l'API REST di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare l'API REST di ONTAP per configurare l'importanza delle notifiche degli eventi del sistema di gestione degli eventi (EMS), nonché per recuperare tutti i messaggi EMS o messaggi specifici con determinati attributi. È possibile utilizzare l'API REST per automatizzare le attività relative a EMS, risparmiando tempo rispetto ad altri metodi di utilizzo dei messaggi EMS.

Gli esempi seguenti mostrano come utilizzare l'API REST di ONTAP per gestire i messaggi EMS. In ogni esempio, assicurarsi di fornire i valori per le informazioni tra parentesi <> dove indicato. È anche possibile fare riferimento a un esempio https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Script Python"^] Ciò dimostra come automatizzare una serie di attività relative a EMS.



== Visualizza registri eventi specifici

Utilizzando il `GET /support/ems/events` Chiamata API, è possibile recuperare messaggi di eventi specifici, come ad esempio l'ultimo messaggio, messaggi contenenti testo specifico o messaggi con una severità specifica.

.Richiesta di esempio: Recuperare l'ultimo messaggio
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.Esempio di risposta
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.Richiesta di esempio: Recuperare un messaggio contenente testo e severità specifici
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.Esempio di risposta
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== Visualizzare la configurazione EMS esistente

Utilizzando il `GET /support/ems/` API Call, consente di recuperare le informazioni sulla configurazione di notifica EMS esistente.

.Richiesta di esempio
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.Esempio di risposta
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== Creare una nuova configurazione di notifica EMS

È possibile utilizzare diverse chiamate API insieme per creare una nuova configurazione EMS per personalizzare la modalità e la data di ricezione dei messaggi.

.Fasi
. Configurare le impostazioni e-mail a livello di sistema. Ad esempio:
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. Definire un filtro che utilizzi regole specifiche per associare determinati messaggi. Ad esempio:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. Creare una destinazione per i messaggi. Ad esempio:
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== API REST ONTAP e comandi CLI ONTAP

L'API REST di ONTAP consente di automatizzare i flussi di lavoro con meno comandi rispetto all'interfaccia CLI di ONTAP per molte attività. Ad esempio, è possibile utilizzare un singolo metodo POST API per creare un filtro, invece di utilizzare più comandi CLI. La seguente tabella mostra i comandi CLI necessari per completare le attività EMS comuni rispetto alle corrispondenti chiamate API REST:

|===
| API REST di ONTAP | CLI ONTAP 


| `GET /support/ems` | `event config show` 


| `POST /support/ems/destinations`  a| 
. `event notification destination create`
. `event notification create`




| `GET /support/ems/events` | `event log show` 


| `POST /support/ems/filters`  a| 
. `event filter create -filter-name <filtername>`
. `event filter rule add -filter-name  <filtername>`


|===


== Informazioni correlate

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["ONTAP REST API esempio di script Python"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["API REST di ONTAP: Notifica automatica degli eventi ad alta severità"^]

